# Generated by Django 2.1.5 on 2019-02-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('apellidosUsuario', models.CharField(max_length=50)),
                ('edadUsuario', models.IntegerField()),
                ('correoUsuario', models.EmailField(max_length=50)),
                ('fechaNacimientoUsuario', models.DateField()),
                ('sexo', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
