# Generated by Django 2.1.5 on 2019-02-21 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20190221_1428'),
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile'),
        ),
    ]
