# Generated by Django 2.1.5 on 2019-02-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitudGps', models.CharField(max_length=50)),
                ('longitudGps', models.CharField(max_length=50)),
                ('fechaGps', models.DateField()),
                ('horaGps', models.TimeField()),
                ('imei', models.CharField(max_length=50)),
            ],
        ),
    ]
